로그인 검증 기능 추가
moons-family/starbucks pull request #4
Opened 2023-03-19 11:34 UTC by MoonInHo

## 로그인 검증기능 추가
- 회원 로그인 기능
- 존재하지 않는 아이디 입력시 에러 메세지 출력
- 비밀번호가 일치하지 않을 경우 에러 메세지 출력과 함께 로그인 시도 가능 횟수 감소
- 로그인 실패 5회 누적시 아이디 잠금
- 로그인 시도 횟수가 남아있을때 로그인에 성공하면 로그인 시도 가능 횟수 초기화

2023-03-19 11:43 UTC, peda007 commented on src/main/java/com/mooninho/starbucks/MemberAPIController.java
> +            throw new UserException("비밀번호가 일치하지 않습니다. 남은 시도 횟수 : " + member.getLoginCount());
값은 LoginCount인데 남은 시도 횟수네
로그인을 한 횟수가 loginCount 같은데, 로그인 실패 횟수로 이름을 지어야 하지 않을까?
e.g. `loginFailCount`

2023-03-19 11:44 UTC, peda007 commented on src/main/java/com/mooninho/starbucks/MemberAPIController.java
> +        Member member = memberService.login(memberLoginDTO);
이 메서드를 실행시키면 로그인이 되는것 같은데 아래 코드를 보니 member정보를 가져오는 것 같네
메서드 이름이 login이면 안될것 같은데 다른걸로 고쳐야 할 듯

2023-03-19 11:44 UTC, MoonInHo commented on src/main/java/com/mooninho/starbucks/MemberAPIController.java
> +            throw new UserException("비밀번호가 일치하지 않습니다. 남은 시도 횟수 : " + member.getLoginCount());
확인했습니다~

2023-03-19 11:45 UTC, peda007 commented on src/main/java/com/mooninho/starbucks/entity/Member.java
> +import javax.persistence.Column;
굿
*로 import하는것은 좋지 않은 습관인데, 의도된건지 모르겠지만 잘 처리 했네

2023-03-19 11:45 UTC, peda007 commented on src/main/java/com/mooninho/starbucks/entity/Member.java
> +    @Column(unique = true)
column 속성 지정 굿 👍 
기타 속성도 가득가득 채워서 이 값에 대한 밸리데이션을 디비에서도 해주면 좋음

2023-03-19 11:49 UTC, peda007 commented on src/main/java/com/mooninho/starbucks/entity/Member.java
> +    private int loginCount = 5;
이제 보니 5를 넣고 하나씩 빼는 로직이었네
`loginCount`는 지금까지 로그인 한 횟수 같은데, 변수명을 바꿔야 할 듯

---
변수명을 짓기 어렵다면 로직 자체가 어렵게 돼있지 않은지 생각해보면 좋음
보통 말을 거꾸로 표현할 때 변수명 짓기가 어렵고, 이 때문에 로직에 대한 복잡도도 같이 올라감
예를들어 위 상황에선 로그인 실패하면 1씩 감소되는 값이고 0보다 적으면 로그인이 불가능하다는것을 변수 이름으로 설명해야 하는데 이게 너무 어렵지??

나는 그래서 loginFailCount로 하고 0으로 설정해놨어
실패할때마다 1씩 증가
5를 초과하면 잠금 처리
이렇게 하면 다른 사람이 읽을 때 훨씬 편한 코드가 되겠지

2023-03-19 11:51 UTC, peda007 commented on src/main/java/com/mooninho/starbucks/entity/Member.java
> +    public int changeLoginCount(int loginCount) {
setter 안쓰고 하는 습관 좋네~
다만 이렇게 하면 다른 개발자가 임의로 10, 0, -5 이런식으로 넣을 수 있는데 이거보단
```java
public int loginFail() {
  this.loginCount -= 1; // loginFailCount 라면 +할텐데 너의 로직 기준에서 작성한거라 이렇게 예시를 씀
}
```
이런 형식이 더 좋음

2023-03-19 11:54 UTC, MoonInHo commented on src/main/java/com/mooninho/starbucks/MemberAPIController.java
> +        Member member = memberService.login(memberLoginDTO);
메서드명 결정할때 뜻이랑 적절한 표현인지 생각해보고 짓겠음

2023-03-19 11:54 UTC, peda007 commented on src/main/java/com/mooninho/starbucks/exceptionhandler/ErrorResult.java
> +public class ErrorResult {
ErrorResult는 에러 결과라는 뜻인데, 이것보단 `ErrorResponseDto` 같은 표현이 좀 더 직관적이지 않을까??
---
참고로 나는 DTO같은 줄임말이라도 카멜케이스 법칙 그대로 적용해서 Dto로 쓰는 편임

2023-03-19 11:57 UTC, peda007 commented on src/main/java/com/mooninho/starbucks/exceptionhandler/UserExHandler.java
> +public class UserExHandler {
`UserExceptionHandler`로 이름 바꾸는게 좋음
Ex가 공식적인 줄임말도 아니고 다른 개발자가 보고 못 알아들을 가능성이 매우 높음
변수나 메서드, 클래스 명 모두 줄임말 없이 풀네임으로 쓰고, 너무 길다면 내가 지금 설계를 잘못하지 않았나 생각해보셈

p.s. 특히 영어권에서의 ex는 ~전 이라는 뜻이 메인(ex-girlfriend 같이) 이기도 함

2023-03-19 11:58 UTC, peda007 commented on src/main/java/com/mooninho/starbucks/exceptionhandler/ErrorResult.java
> +    private String code;
코드가 많아지면 이런 코드들은 String으로 관리했을 때 난장판이 되기 일수임
왜 그런지는 생각해볼것

2023-03-19 11:59 UTC, peda007 commented on src/main/java/com/mooninho/starbucks/repository/MemberRepository.java
> +    Member findByEmail(String email);
간단한거라도 querydsl로 모든 쿼리를 작성하는 습관을 들이는게 좋음
메서드 네이밍 쿼리는 복잡도가 높고 효율이 좋지 않은 경우가 많아서 (exist등) querydsl로 작성하길

2023-03-19 12:04 UTC, MoonInHo commented on src/main/java/com/mooninho/starbucks/entity/Member.java
> +    public int changeLoginCount(int loginCount) {
그럼 로그인 성공시 시도가능횟수를 초기화해주는 메서드를 따로 생성하는게 나은 방법인가??

2023-03-19 12:06 UTC, peda007 commented on src/main/java/com/mooninho/starbucks/service/MemberService.java
> +    public static Member createMember(MemberJoinDTO memberJoinDto) {
객체 생성과 관련해서
- builder pattern
- static factory method pattern
찾아보셈

2023-03-19 12:08 UTC, peda007 reviewed
클래스 파일들이 같이 올라가고 있는데 .gitignore 확인하고 수정 하길

2023-03-19 12:08 UTC, peda007 commented on src/main/java/com/mooninho/starbucks/entity/Member.java
> +    public int changeLoginCount(int loginCount) {
@MoonInHo 내용 업뎃 해놨음

2023-03-19 12:30 UTC, MoonInHo commented on src/main/java/com/mooninho/starbucks/exceptionhandler/ErrorResult.java
> +    private String code;
에러코드가 너무 많아져서 해당하는 코드를 찾기 힘들어서 일거같은데 그럼 enum타입을 따로 생성해서 코드를 불러오는 방법이 좋을수도 있겠네

2023-03-19 14:17 UTC, peda007 requested changes
.DS_Store도 쓸데없이 올라가는데 gitignore 추가하고, 
login인데 로그인을 하는 부분이 정작 없어보임..!

2023-03-20 15:24 UTC, peda007 commented on src/main/java/com/mooninho/starbucks/MemberAPIController.java
> +        session.setAttribute("loginMember", loginMember);
굿 잘 해결했네
근데 session에 들어가는 member 객체는 영속화 되지 않은 엔티티라 lazy loading등으로 인한 exception이 발생할 가능성이 있음
따라서 dto로 변환해서 넣거나 id만 세션에 넣는게 어떨까??

2023-03-20 15:43 UTC, peda007 approved these changes

2023-03-20 15:43 UTC, peda007 commented
고생 많았음 👍

2023-03-24 03:17 UTC, merged