TDD 기반 회원 가입 기능 개발
moons-family/starbucks pull request #7
Opened 2023-04-03 07:22 UTC by MoonInHo

## 회원가입 기능 개발
- 회원 도메인 테스트코드 추가
- 회원가입 서비스 테스트 코드 추가
- 리팩토링

2023-04-03 14:05 UTC, peda007 commented on src/main/java/com/mooninho/starbucks/v1/repository/MemberQueryRepositoryV1.java
> +
엔터 삭제 좀

2023-04-03 14:06 UTC, peda007 commented on src/main/java/com/mooninho/starbucks/v1/repository/MemberQueryRepositoryV1.java
> +        this.queryFactory = new JPAQueryFactory(em);
이걸 bean으로 등록하면 매번 JPAQueryFactory를 만들 필요가 없어짐

2023-04-03 14:10 UTC, MoonInHo commented on src/main/java/com/mooninho/starbucks/v1/repository/MemberQueryRepositoryV1.java
> +        this.queryFactory = new JPAQueryFactory(em);
오 좋은방법이네 반영해볼게

2023-04-03 14:11 UTC, peda007 commented on src/main/java/com/mooninho/starbucks/v1/service/MemberServiceV1.java
> +    public DeleteMemberInfoV1 deleteMember(Long id, String reason, HttpSession session) {
사람마다 구현하기 나름이겠지만 나는 Session 의존도가 서비스에 있는게 좋다고 생각 안 해
presentation layer(controller 영역)에서 관리되는 항목이라고 생각이 들고 이렇게 쓰면 재활용성도 떨어진다고 생각해서..

회원 탈퇴 Service는 "탈퇴"에 집중하는것도 좋을것 같네

2023-04-03 14:13 UTC, peda007 commented on src/main/java/com/mooninho/starbucks/v2/domain/Email.java
> +        this("");
이건 왜 있는거야..?
email 값이 blank가 되지 않도록 잘 만들어놓고 직접 empty를 넣어주는 코드를 작성했네??

2023-04-03 14:14 UTC, peda007 commented on src/main/java/com/mooninho/starbucks/v2/dto/MemberJoinDto.java
> +        if (!memberDto.getEmail().matches("^(?:\\w+\\.?)*\\w+@(?:\\w+\\.)+\\w+$")) {
여기서 이 검사를 왜 하는지 모르겠네.
dto는 비지니스 로직이 들어가는 부분이 아니고 데이터를 옮기는것에 충실해야 해

2023-04-03 14:14 UTC, MoonInHo commented on src/main/java/com/mooninho/starbucks/v2/domain/Email.java
> +        this("");
private로 지정해서 외부접근 막고 기본생성자가 없어서 읽어들이지를 못하길래 추가했음

2023-04-03 14:14 UTC, peda007 commented on src/main/java/com/mooninho/starbucks/v2/entity/Member.java
> +                optionalName(name),
내가 급하게 지은건데 그대로 쓰지 말고 좀 더 고민해보면 좋았을 걸 🙁

2023-04-03 14:16 UTC, peda007 commented on src/main/java/com/mooninho/starbucks/v2/repository/MemberQueryRepository.java
> +        return result.map(r -> r == 1).orElse(false);
간단한 코드를 왜 이렇게 복잡하게 짰는지 모르겠네..
읽을 때 이 로직의 흐름을 이해할 필요가 없이 간결하게 짜야해
아래처럼 내가 짜줬던것 같은데 이렇게 바꿀 필요가 있었을까??
```java
return queryFactory
                 .selectOne()
                 .from(member)
                 .where(member.email.eq(Email.of(email)))
                 .fetchFirst() == 1
```

2023-04-03 14:19 UTC, peda007 commented on src/test/java/com/mooninho/starbucks/v2/domain/MemberDomainTest.java
> +        MemberJoinDto memberJoinDto = MemberJoinDto.setMemberInfo(memberDto);
set 보다는 create나 of 같은걸 쓰는게 좋아
정적 팩토리 메서드 패턴에 대해 이름 규칙(naming convention)을 찾아보면 좋을것 같고, 이걸 사용함으로써 객체가 생성된다는 느낌을 받는게 좋아. MemberJoinDto가 생성되는 코드니까

2023-04-03 14:19 UTC, peda007 commented on src/test/java/com/mooninho/starbucks/v2/service/MemberServiceTest.java
> +        given(memberRepository.save(any()))
이번 일을 계기로 mock에 대해 완전히 익혔길..!

2023-04-03 14:22 UTC, peda007 commented on src/main/java/com/mooninho/starbucks/v2/domain/Email.java
> +        this("");
기본 생성자의 경우 아래 처럼 어노테이션을 사용할 수도 있고 안의 내용을 아무것도 명시 안해도 돼.
```java
@NoArgsConstructor(access = AccessLevel.PRIVATE)
public class Something {
  ...
}
```

```java
private Email() {}
```

2023-04-03 14:23 UTC, MoonInHo commented on src/main/java/com/mooninho/starbucks/v2/repository/MemberQueryRepository.java
> +        return result.map(r -> r == 1).orElse(false);
NPE가 발생해서 옵셔널로 감쌌음!

2023-04-03 14:35 UTC, peda007 commented on src/main/java/com/mooninho/starbucks/v2/repository/MemberQueryRepository.java
> +        return result.map(r -> r == 1).orElse(false);
?? NPE가 어디서 발생해??
fetchFirst에서 null이 떠도 == 1에서 false를 리턴하게 되는데..?

2023-04-03 15:03 UTC, MoonInHo commented on src/main/java/com/mooninho/starbucks/v2/domain/Email.java
> +        this("");
그렇게 하려했더니 기본생성자에 아무값도 입력이 안되면 불확실성때문에 final이 적용안된다길래 빈문자열로 넣었는듯!

2023-04-03 15:04 UTC, MoonInHo commented on src/main/java/com/mooninho/starbucks/v2/dto/MemberJoinDto.java
> +        if (!memberDto.getEmail().matches("^(?:\\w+\\.?)*\\w+@(?:\\w+\\.)+\\w+$")) {
리팩토링할때 반영해보겠음

2023-04-03 15:05 UTC, MoonInHo commented on src/main/java/com/mooninho/starbucks/v2/entity/Member.java
> +                optionalName(name),
여기에대해선 아직 고민중이고 가입기능 모든 부분이 완성이 아니라 단순기능 하나만 완료한거라 추가로 작업할때 고쳐볼게

2023-04-03 16:21 UTC, MoonInHo commented on src/main/java/com/mooninho/starbucks/v1/repository/MemberQueryRepositoryV1.java
> +
이거 V1이네ㄷㄷ 일단 확인

2023-04-03 16:43 UTC, MoonInHo commented on src/main/java/com/mooninho/starbucks/v1/service/MemberServiceV1.java
> +    public DeleteMemberInfoV1 deleteMember(Long id, String reason, HttpSession session) {
V1에서 반영했던거라 V2에서 구현할때 해당 피드백 반영해서 구현해볼게

2023-04-04 05:55 UTC, MoonInHo commented on src/main/java/com/mooninho/starbucks/v2/entity/Member.java
> +                optionalName(name),
고민하다 보니까 의도하고 좀 다른 구조라서 일단 삭재했음!

2023-04-04 05:57 UTC, MoonInHo commented on src/main/java/com/mooninho/starbucks/v2/repository/MemberQueryRepository.java
> +        return result.map(r -> r == 1).orElse(false);
찾아보니까 fetchFirst 값이 null 일경우 == 1 로 비교연산을 해도 null을 반환해고 null값을 따로 처리해주는 로직이 필요하다고 해서 return할때 null처리코드를 추가해서 커밋했음

2023-04-04 09:44 UTC, peda007 commented on src/main/java/com/mooninho/starbucks/v2/repository/MemberQueryRepository.java
> +        return result.map(r -> r == 1).orElse(false);
이상하네 그럴리가 없는데
음.. 이건 나중에 직접 보여주면 좋을 듯

2023-04-04 09:45 UTC, peda007 commented on src/main/java/com/mooninho/starbucks/v2/StarbucksConfiguration.java
> +    public JPAQueryFactory jpaQueryFactory() {
굿 깔끔하게 필요한 내용만 넣어서 잘 만들었네~ 👍

2023-04-04 09:47 UTC, peda007 commented on src/main/java/com/mooninho/starbucks/v2/controller/MemberAPIController.java
> +        if (!memberDto.getEmail().matches("^(?:\\w+\\.?)*\\w+@(?:\\w+\\.)+\\w+$")) {
🤔

2023-04-04 09:52 UTC, peda007 requested changes
고생햇음

2023-04-04 09:52 UTC, peda007 approved these changes

2023-04-05 00:40 UTC, MoonInHo commented
컨펌 감사

2023-04-05 00:40 UTC, merged